const productList = [
  {
    _id: 1,
    name: "밀레 거실등 LED180W (SP222)LR",
    price: 105000,
    producer: "조명뱅크",
    type: "거실조명",
    image: "img/shop/product/1.png",
  },
  {
    _id: 2,
    name: "프링 6등 인테리어조명(샹들리에) 파이프형식",
    price: 50150,
    producer: "비츠",
    type: "방조명",
    image: "img/shop/product/2.png",
  },
  {
    _id: 3,
    name: "PH 43 팬던트",
    price: 68000,
    producer: "제일조명",
    type: "주방조명",
    image: "img/shop/product/3.png",
  },
  {
    _id: 4,
    name: "태양광 정원등 13구 야외LED조명_5types",
    price: 41650,
    producer: "신성나라",
    type: "현관/배란다조명",
    image: "img/shop/product/4.png",
  },
  {
    _id: 5,
    name: "LED 에잇 직부등 2등/3등/4등/5등",
    price: 55930,
    producer: "바이빔",
    type: "레일조명",
    image: "img/shop/product/5.png",
  },
  {
    _id: 6,
    name: "코니아일랜드 장스탠드",
    price: 31450,
    producer: "올루미",
    type: "장스탠드",
    image: "img/shop/product/6.png",
  },
  {
    _id: 7,
    name: "오로라 단스탠드(전구 증정 이벤트, 5월 패키지 무료포장)",
    price: 18700,
    producer: "올루미",
    type: "단스탠드",
    image: "img/shop/product/7.png",
  },
  {
    _id: 8,
    name: "파파 LED 와이드스탠드_2colors",
    price: 33465,
    producer: "베스트조명",
    type: "데스크스탠드",
    image: "img/shop/product/8.png",
  },
  {
    _id: 9,
    name: "빈티지 원목 벽등_2colors",
    price: 20400,
    producer: "참라이팅",
    type: "벽조명",
    image: "img/shop/product/9.png",
  },
  {
    _id: 10,
    name: "미나L LED 버섯램프_9colors(무선충전,생활방수) - LH65",
    price: 74800,
    producer: "LEXON(렉슨)",
    type: "무드등/장식조명",
    image: "img/shop/product/10.png",
  },
];

export default productList;
