const ProductList = [
  {
    _id: 1,
    name: "삼정라이팅 스퀘어 2단 식탁등",
    desc: "고급스러운 멋이 살아나요",
    price: 219000,
    type: "거실조명",
    image: "img/shop/product/1.jpg",
  },
  {
    _id: 2,
    name: "루이스 PH5 인테리어조명(大,小)",
    desc: "하이엔드를 원한다면 필구",
    price: 129000,
    type: "방조명",
    image: "img/shop/product/2.jpg",
  },
  {
    _id: 3,
    name: "글로시 1등 인테리어조명",
    desc: "레트로 감성이 살아나요",
    price: 54900,
    type: "주방조명",
    image: "img/shop/product/3.jpg",
  },
  {
    _id: 4,
    name: "브리앙뜨 1등 인테리어조명",
    desc: "클래식한 홈을 원하는 당신에게",
    price: 119000,
    type: "현관/배란다조명",
    image: "img/shop/product/4.jpg",
  },
  {
    _id: 5,
    name: "베른 1등 인테리어조명",
    price: 69000,
    type: "레일조명",
    desc: "섬세한 디자인의 멋",
    image: "img/shop/product/5.jpg",
  },
  {
    _id: 6,
    name: "베르디 PH4 1등 인테리어조명",
    desc: "북유럽 감성을 내 집에",
    price: 109000,
    type: "장스탠드",
    image: "img/shop/product/6.jpg",
  },
  {
    _id: 7,
    name: "아르망 1등 인테리어조명",
    desc: "가치를 창출하는 조명",
    price: 189000,
    type: "단스탠드",
    image: "img/shop/product/7.jpg",
  },
  {
    _id: 8,
    name: "루몽 1등 인테리어조명",
    desc: "공간에 가치를 더하다",
    price: 189000,
    type: "데스크스탠드",
    image: "img/shop/product/8.jpg",
  },
  {
    _id: 9,
    name: "레이어 1등 인테리어조명",
    desc: "북유럽을 집에서 만나자",
    price: 20400,
    type: "벽조명",
    image: "img/shop/product/9.jpg",
  },
  {
    _id: 10,
    name: "루첸 1등 인테리어조명",
    producer: "모던한 컬러 조명",
    price: 150000,
    type: "무드등/장식조명",
    image: "img/shop/product/10.jpg",
  },
  {
    _id: 11,
    name: "가토 1등 인테리어조명",
    desc: "심플함과 섬세함이 살아있는 조명",
    price: 39000,
    type: "무드등/장식조명",
    image: "img/shop/product/11.jpg",
  },
  {
    _id: 12,
    name: "블로앙 1등 식탁등",
    price: 29000,
    producer: "심플함이 주는 끝없는 매력",
    type: "무드등/장식조명",
    image: "img/shop/product/12.jpg",
  },
  {
    _id: 13,
    name: "루크 1등 인테리어조명(大,小)",
    desc: "부드러움 감성 조명",
    price: 51000,
    type: "무드등/장식조명",
    image: "img/shop/product/13.jpg",
  },
  {
    _id: 14,
    name: "버블 1등 인테리어조명",
    desc: "이용자 최다 추천 조명",
    price: 23000,
    type: "무드등/장식조명",
    image: "img/shop/product/14.jpg",
  },
];

const nonDescProduct = [
  {
    _id: 15,
    name: "FINXIN 드럼형 플로어 스탠드 (단일 색상) ",
    price: 65000,
    type: "무드등/장식조명",
    image: "img/shop/product/15.jpg",
  },
  {
    _id: 16,
    name: "롬앤글라스 다크우드 LED 조명 윈디",
    price: 59000,
    type: "무드등/장식조명",
    image: "img/shop/product/16.jpg",
  },
  {
    _id: 17,
    name: "이케아 TALLBYN 텔뷘 플로어스탠드, 니켈 도금, 오팔 화이트 유리, 135cm ",
    price: 59000,
    type: "무드등/장식조명",
    image: "img/shop/product/17.jpg",
  },
  {
    _id: 18,
    name: "이고라이팅 FADO 파도 달 조명, 2size, 2colors (박스 안전포장)",
    price: 15200,
    type: "무드등/장식조명",
    image: "img/shop/product/18.jpg",
  },
  {
    _id: 19,
    name: "나르디아 6등 팬던트조명",
    price: 165000,
    type: "무드등/장식조명",
    image: "img/shop/product/19.jpg",
  },
  {
    _id: 20,
    name: "엔틱 하이드 5등 팬던트조명",
    price: 229000,
    type: "무드등/장식조명",
    image: "img/shop/product/20.jpg",
  },
  {
    _id: 21,
    name: "아라미스 8등 팬던트조명",
    price: 255000,
    type: "무드등/장식조명",
    image: "img/shop/product/21.jpg",
  },
  {
    _id: 22,
    name: "미노스 1등 팬던트조명",
    price: 55100,
    type: "무드등/장식조명",
    image: "img/shop/product/22.jpg",
  },
  {
    _id: 23,
    name: "버블 1등 인테리어조명",
    price: 23000,
    type: "무드등/장식조명",
    image: "img/shop/product/23.jpg",
  },
  {
    _id: 24,
    name: "버블 1등 인테리어조명",
    price: 23000,
    type: "무드등/장식조명",
    image: "img/shop/product/24.jpg",
  },
];

export { ProductList, nonDescProduct };
